<?php

/**
 * ProcessWire Configuration File
 *
 * Site-specific configuration for ProcessWire.
 * This config.php file was generated by the ProcessExportProfile module. 
 *
 * Please see the file /wire/config.php which contains all configuration options you may
 * specify here. Simply copy any of the configuration options from that file and paste
 * them into this file in order to modify them.
 *
 * ProcessWire 
 * Copyright (C) 2017 by Ryan Cramer
 * Licensed under MPL 2.0
 *
 * https://processwire.com
 *
 */

if(!defined("PROCESSWIRE")) die();

/*** SITE CONFIG *************************************************************************/

$config->prependTemplateFile = '_init.php';
$config->appendTemplateFile = '_main.php';
$config->useMarkupRegions = true;
$config->useFunctionsAPI = true;
$config->defaultAdminTheme = 'AdminThemeUikit';

/**
 * Example Custom Config
 * https://processwire.com/api/variables/config/
 * https://processwire.com/blog/posts/pw-3.0.87/#new-field-template-context-settings
 */

/** Advanced Configuration **/
// $config->advanced = true;

/** Show demo site **/
// $config->demo = true;

/** https://processwire.com/blog/posts/pw-3.0.99/ **/
// $config->noHTTPS = true;

/**  ignore HTTPS for this hostname only: **/
// $config->noHTTPS = 'dev.processwire.com';

/** ignore HTTPS for these hostnames: **/
//     $config->noHTTPS = [
//       'dev.processwire.com',
//       'stage.processwire.com',
//       'localhost:8888',
//     ];

/*** INSTALLER CONFIG ********************************************************************/



/**
 * Installer: Database Configuration
 * 
 */
$config->dbHost = 'localhost';
$config->dbName = 'caancom_caan4';
$config->dbUser = 'caancom';
$config->dbPass = 'UuPBjwbA';
$config->dbPort = '3306';

/**
 * Installer: User Authentication Salt 
 * 
 * This value was randomly generated for your system on 2020/09/04.
 * This should be kept as private as a password and never stored in the database.
 * Must be retained if you migrate your site from one server to another.
 * Do not change this value, or user passwords will no longer work.
 * 
 */
$config->userAuthSalt = '28216d040d8661e446fae68b252c40e2627e8708'; 

/**
 * Installer: Table Salt (General Purpose) 
 * 
 * Use this rather than userAuthSalt when a hashing salt is needed for non user 
 * authentication purposes. Like with userAuthSalt, you should never change 
 * this value or it may break internal system comparisons that use it. 
 * 
 */
$config->tableSalt = '9dc26de076e8cfb3539d179aa0e62033604123dd'; 

/**
 * Installer: File Permission Configuration
 * 
 */
$config->chmodDir = '0755'; // permission for directories created by ProcessWire
$config->chmodFile = '0644'; // permission for files created by ProcessWire 

/**
 * Installer: Time zone setting
 * 
 */
$config->timezone = 'Asia/Ho_Chi_Minh';

/**
 * Installer: Admin theme
 * 
 */
$config->defaultAdminTheme = 'AdminThemeUikit';

/**
 * Installer: Unix timestamp of date/time installed
 * 
 * This is used to detect which when certain behaviors must be backwards compatible.
 * Please leave this value as-is.
 * 
 */
$config->installed = 1599217573;


/**
 * Installer: HTTP Hosts Whitelist
 * 
 */
$config->httpHosts = array('cacom4.caandev.com,caan.com.vn,www.caan.com.vn');


/**
 * Installer: Debug mode?
 * 
 * When debug mode is true, errors and exceptions are visible. 
 * When false, they are not visible except to superuser and in logs. 
 * Should be true for development sites and false for live/production sites. 
 * 
 */
$config->debug = true;

